function loadTextures(){
    loader.add("dungeonTiles", "assets/textures/tiles/dungeon-tile.png")
    loader.add("cursor", "assets/textures/cursor.png")
    loader.add("grid_32_32", "assets/textures/grids/32-32-grid.png")
    loader.add("table_1", "assets/textures/objects/TC_Basics_Asset_Pack/TC_Basics Asset Pack_Table1.png")
    loader.add("barrel_1", "assets/textures/objects/TC_Basics_Asset_Pack/TC_Basics Asset Pack_Barrel1.png")
}
function loadTiles(){
    
    // Loads Dungeon tiles
    // Row 1
    textures.tiles.bottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomright.frame = new PIXI.Rectangle(0, 0, 32, 32)
    textures.tiles.bottom = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottom.frame = new PIXI.Rectangle(32, 0, 32, 32)
    textures.tiles.bottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomleft.frame = new PIXI.Rectangle(32 * 2, 0, 32, 32)
    textures.tiles.right = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.right.frame = new PIXI.Rectangle(32 * 3, 0, 32, 32)
    textures.tiles.center = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.center.frame = new PIXI.Rectangle(32 * 4, 0, 32, 32)
    textures.tiles.left = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.left.frame = new PIXI.Rectangle(32 * 5, 0, 32, 32)
    textures.tiles.topright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topright.frame = new PIXI.Rectangle(32 * 6, 0, 32, 32)
    // Row 2
    textures.tiles.top = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.top.frame = new PIXI.Rectangle(0, 32, 32, 32)
    textures.tiles.topleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleft.frame = new PIXI.Rectangle(32, 32, 32, 32)
    textures.tiles.swingUpRight = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingUpRight.frame = new PIXI.Rectangle(32 * 2, 32, 32, 32)
    textures.tiles.swingRightDown = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingRightDown.frame = new PIXI.Rectangle(32 * 3, 32, 32, 32)
    textures.tiles.swingRightUp = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingRightUp.frame = new PIXI.Rectangle(32 * 4, 32, 32, 32)
    textures.tiles.swingDownRight = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingDownRight.frame = new PIXI.Rectangle(32 * 5, 32, 32, 32)
    textures.tiles.UFromLeft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.UFromLeft.frame = new PIXI.Rectangle(32 * 6, 32, 32, 32)
    // Row 3
    textures.tiles.UFromTop = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.UFromTop.frame = new PIXI.Rectangle(0, 32 * 2, 32, 32)
    textures.tiles.UFromRight = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.UFromRight.frame = new PIXI.Rectangle(32, 32 * 2, 32, 32)
    textures.tiles.UFromBottom = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.UFromBottom.frame = new PIXI.Rectangle(32 * 2, 32 * 2, 32, 32)
    textures.tiles.circle = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.circle.frame = new PIXI.Rectangle(32 * 3, 32 * 2, 32, 32)
    textures.tiles.swingUpRightBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingUpRightBottomright.frame = new PIXI.Rectangle(32 * 4, 32 * 2, 32, 32)
    textures.tiles.swingRightDownBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingRightDownBottomleft.frame = new PIXI.Rectangle(32 * 5, 32 * 2, 32, 32)
    textures.tiles.swingRightUpTopleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingRightUpTopleft.frame = new PIXI.Rectangle(32 * 6, 32 * 2, 32, 32)
    // Row 4
    textures.tiles.swingDownRightTopright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.swingDownRightTopright.frame = new PIXI.Rectangle(0, 32 * 3, 32, 32)
    textures.tiles.leftRight = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.leftRight.frame = new PIXI.Rectangle(32, 32 * 3, 32, 32)
    textures.tiles.topBottom = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topBottom.frame = new PIXI.Rectangle(32 * 2, 32 * 3, 32, 32)
    textures.tiles.leftTopright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.leftTopright.frame = new PIXI.Rectangle(32 * 3, 32 * 3, 32, 32)
    textures.tiles.leftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.leftBottomright.frame = new PIXI.Rectangle(32 * 4, 32 * 3, 32, 32)
    textures.tiles.topBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topBottomleft.frame = new PIXI.Rectangle(32 * 5, 32 * 3, 32, 32)
    textures.tiles.topBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topBottomright.frame = new PIXI.Rectangle(32 * 6, 32 * 3, 32, 32)
    // Row 5
    textures.tiles.rightTopleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.rightTopleft.frame = new PIXI.Rectangle(32 * 0, 32 * 4, 32, 32)
    textures.tiles.rightBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.rightBottomleft.frame = new PIXI.Rectangle(32 * 1, 32 * 4, 32, 32)
    textures.tiles.bottomTopright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomTopright.frame = new PIXI.Rectangle(32 * 2, 32 * 4, 32, 32)
    textures.tiles.bottomTopleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomTopleft.frame = new PIXI.Rectangle(32 * 3, 32 * 4, 32, 32)
    textures.tiles.LeftToprightBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.LeftToprightBottomright.frame = new PIXI.Rectangle(32 * 4, 32 * 4, 32, 32)
    textures.tiles.topBottomleftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topBottomleftBottomright.frame = new PIXI.Rectangle(32 * 5, 32 * 4, 32, 32)
    textures.tiles.rightTopleftBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.rightTopleftBottomleft.frame = new PIXI.Rectangle(32 * 6, 32 * 4, 32, 32)
    // Row 6
    textures.tiles.bottomTopleftTopright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomTopleftTopright.frame = new PIXI.Rectangle(32 * 0, 32 * 5, 32, 32)
    textures.tiles.topleftTopright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftTopright.frame = new PIXI.Rectangle(32 * 1, 32 * 5, 32, 32)
    textures.tiles.topleftBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftBottomleft.frame = new PIXI.Rectangle(32 * 2, 32 * 5, 32, 32)
    textures.tiles.bottomLeftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.bottomLeftBottomright.frame = new PIXI.Rectangle(32 * 3, 32 * 5, 32, 32)
    textures.tiles.toprightBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.toprightBottomright.frame = new PIXI.Rectangle(32 * 4, 32 * 5, 32, 32)
    textures.tiles.topleftToprightBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftToprightBottomright.frame = new PIXI.Rectangle(32 * 5, 32 * 5, 32, 32)
    textures.tiles.topleftToprightBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftToprightBottomleft.frame = new PIXI.Rectangle(32 * 6, 32 * 5, 32, 32)
    textures.tiles.topleftBottomleftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    // Row 7
    textures.tiles.topleftBottomleftBottomright.frame = new PIXI.Rectangle(32 * 0, 32 * 6, 32, 32)
    textures.tiles.toprightBottomleftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.toprightBottomleftBottomright.frame = new PIXI.Rectangle(32 * 1, 32 * 6, 32, 32)
    textures.tiles.toprightBottomleft = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.toprightBottomleft.frame = new PIXI.Rectangle(32 * 2, 32 * 6, 32, 32)
    textures.tiles.topleftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftBottomright.frame = new PIXI.Rectangle(32 * 3, 32 * 6, 32, 32)
    textures.tiles.topleftToprightBottomleftBottomright = PIXI.utils.TextureCache.dungeonTiles.clone()
    textures.tiles.topleftToprightBottomleftBottomright.frame = new PIXI.Rectangle(32 * 4, 32 * 6, 32, 32)
}
function loadObjects(){
    textures.objects.table_1 = PIXI.utils.TextureCache.table_1.clone()
    textures.objects.barrel_1 = PIXI.utils.TextureCache.barrel_1.clone()
    textures.objects.cursor = PIXI.utils.TextureCache.cursor.clone()
}